#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LEGACY_SDK_RS="${ROOT_DIR}/../privchat-sdk/crates/privchat-sdk/src/sdk.rs"
NEW_FFI_RS="${ROOT_DIR}/crates/privchat-sdk-ffi/src/lib.rs"
OUT_MD="${ROOT_DIR}/docs/api-gap-report.md"

if [[ ! -f "${LEGACY_SDK_RS}" ]]; then
  echo "missing legacy sdk file: ${LEGACY_SDK_RS}" >&2
  exit 1
fi

if [[ ! -f "${NEW_FFI_RS}" ]]; then
  echo "missing new ffi file: ${NEW_FFI_RS}" >&2
  exit 1
fi

legacy_methods="$(mktemp)"
new_methods="$(mktemp)"
missing_methods="$(mktemp)"
trap 'rm -f "${legacy_methods}" "${new_methods}" "${missing_methods}"' EXIT

# Legacy public async/blocking methods as migration source set.
rg -n 'pub (async )?fn ' "${LEGACY_SDK_RS}" \
  | sed -E 's/.*pub (async )?fn ([a-zA-Z0-9_]+).*/\2/' \
  | sort -u > "${legacy_methods}"

# New FFI exported methods (best-effort parser).
rg -n 'pub (async )?fn ' "${NEW_FFI_RS}" \
  | sed -E 's/.*pub (async )?fn ([a-zA-Z0-9_]+).*/\2/' \
  | sort -u > "${new_methods}"

comm -23 "${legacy_methods}" "${new_methods}" > "${missing_methods}" || true

legacy_count="$(wc -l < "${legacy_methods}" | tr -d ' ')"
new_count="$(wc -l < "${new_methods}" | tr -d ' ')"
missing_count="$(wc -l < "${missing_methods}" | tr -d ' ')"

{
  echo "# API Gap Report"
  echo
  echo "Generated by \`scripts/update-api-gap-report.sh\`."
  echo
  echo "- legacy public methods: ${legacy_count}"
  echo "- new ffi public methods: ${new_count}"
  echo "- names missing in new ffi (exact-name compare): ${missing_count}"
  echo
  echo "## Notes"
  echo
  echo "- This report uses exact method-name comparison only."
  echo "- Wrapper-style migrations (e.g. \`*_remote\`, \`rpc_call\`) may still cover legacy capabilities."
  echo "- Use this as a triage signal, not a hard correctness proof."
  echo
  echo "## Missing Names"
  echo
  if [[ "${missing_count}" -eq 0 ]]; then
    echo "- (none)"
  else
    while IFS= read -r name; do
      [[ -z "${name}" ]] && continue
      echo "- \`${name}\`"
    done < "${missing_methods}"
  fi
} > "${OUT_MD}"

echo "wrote ${OUT_MD}"
